# Name of the workflow
name: Docker Build and Push

# This workflow runs on every push to the "main" branch
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant permissions for the workflow to write packages (Docker images)
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to the GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # The username is your GitHub username or organization name
          username: ${{ github.actor }}
          # The password is a special GITHUB_TOKEN that Actions creates automatically
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build the Docker image and push it to the registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The build context is the root of the repository
          context: .
          # Push the image to the registry after building
          push: true
          # Define the tags for the image. It will be tagged with the commit SHA and "latest".
          # Example: ghcr.io/your-username/your-repo-name:a1b2c3d
          #      and ghcr.io/your-username/your-repo-name:latest
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          # Enable build cache for faster subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
